wandb_version: 1

actor_lr:
  value: 0.0001
algo:
  value: ddpg
batch_size:
  value: 256
critic_lr:
  value: 0.0001
device:
  value: cuda
epochs:
  value: 1000
gamma:
  value: 0.99
tau:
  value: 0.03
