wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1662292787.985148
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.10.4
      5: 0.13.1
      8:
      - 5
actor_lr:
  desc: null
  value: 0.0001
algo:
  desc: null
  value: ddpg
batch_size:
  desc: null
  value: 256
critic_lr:
  desc: null
  value: 0.0002
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 1000
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.01
